#! /bin/bash
tmpscript=`cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32`
tmpscript="/tmp/"$tmpscript
callsign=`sed '1q;d' /etc/hamds18b20.conf`
filename=`sed '2q;d' /etc/hamds18b20.conf`
passcode=`sed '3q;d' /etc/hamds18b20.conf`
aprshost=`sed '4q;d' /etc/hamds18b20.conf`
frametext=`hamds18b20 -f $filename  -lc $callsign`
frame=$callsign">APRS:"$frametext
logintext="user $callsign pass $passcode vers hamDS18B20 1.0"
echo '#!/bin/bash' > $tmpscript
echo "echo '$logintext'" >> $tmpscript
echo "sleep 2" >> $tmpscript
echo "echo '$frame'" >> $tmpscript
chmod +x $tmpscript
$tmpscript | socat - TCP:$aprshost
rm -f $tmpscript

