#!/bin/bash
callsign=`sed '1q;d' /etc/hamds18b20.conf`
filename=`sed '2q;d' /etc/hamds18b20.conf`
port=`sed '3q;d' /etc/hamds18b20.conf`
frametext=`hamds18b20 -f $filename  -ec $callsign`
/usr/sbin/beacon -c $callsign -d "TEMPER" -s $port "$frametext"

